2020-12-01 14:32:12,790 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:32:13,477 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:32:13,482 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:32:13,486 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:32:13,842 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:32:14,512 - root - ERROR - task_controler.py:159 - None
2020-12-01 14:33:59,334 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:33:59,931 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:33:59,935 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:33:59,937 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:34:00,109 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:34:00,787 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:34:00,809 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:34:01,000 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:34:50,854 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:34:51,450 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:34:51,461 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:34:51,464 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:34:51,474 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:34:51,580 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:35:33,760 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:35:34,361 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:35:34,364 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:35:34,366 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:35:34,564 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:36:30,219 - root - ERROR - Object2.py:61 - 'int' object has no attribute 'hex'
2020-12-01 14:38:45,500 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:38:46,105 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:38:46,108 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:38:46,111 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:38:46,125 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:38:47,014 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:38:54,280 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:38:56,340 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:39:24,054 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:39:25,053 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:39:26,053 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:42:26,006 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:42:26,608 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:42:26,611 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:42:26,616 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:42:26,631 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:42:27,061 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:43:29,997 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:43:30,594 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:43:30,598 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:43:30,600 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:43:30,611 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:43:31,013 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:43:43,886 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:43:59,040 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:44:00,038 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:47:03,355 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:47:04,001 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:47:04,004 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:47:04,010 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:47:04,014 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:47:04,018 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:47:04,022 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:47:38,147 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:47:49,195 - root - ERROR - Object2.py:61 - 'int' object has no attribute 'hex'
2020-12-01 14:47:52,357 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:48:07,776 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:48:08,790 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:48:14,972 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:48:19,154 - root - ERROR - Object2.py:61 - 'int' object is not iterable
2020-12-01 14:48:20,310 - root - ERROR - Object2.py:61 - 'int' object is not iterable
2020-12-01 14:48:21,463 - root - ERROR - Object2.py:61 - 'int' object is not iterable
2020-12-01 14:48:22,617 - root - ERROR - Object2.py:61 - 'int' object is not iterable
2020-12-01 14:48:23,780 - root - ERROR - Object2.py:61 - 'int' object is not iterable
2020-12-01 14:49:17,861 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:49:18,459 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:49:18,463 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:49:18,466 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:49:18,484 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:49:18,487 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:49:57,277 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:49:57,877 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:49:57,880 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:49:57,883 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:49:58,591 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:50:14,562 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:50:15,160 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:50:15,163 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:50:15,166 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:50:30,617 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:50:31,270 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:50:31,273 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:50:31,275 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:50:31,285 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:50:31,293 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:50:32,131 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:51:12,670 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:51:13,267 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:51:13,270 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:51:13,273 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:51:13,280 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:51:13,290 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:51:13,408 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:52:21,056 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:52:21,663 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:52:21,666 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:52:21,669 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:52:21,678 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:52:22,433 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:52:59,375 - root - INFO - main.py:60 - START SERVER
2020-12-01 14:52:59,974 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 14:52:59,977 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 14:52:59,979 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 14:53:00,800 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 14:53:16,096 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:53:32,520 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 14:53:34,247 - root - ERROR - Object2.py:61 - 'int' object has no attribute 'hex'
2020-12-01 15:00:30,693 - root - INFO - main.py:60 - START SERVER
2020-12-01 15:00:31,343 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.201', 4370))已成功连接。。
2020-12-01 15:00:31,347 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.97', 23))已成功连接。。
2020-12-01 15:00:31,349 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 15:00:31,354 - root - INFO - gateway_server.py:236 - 服务端(('192.168.0.117', 23))已成功连接。。
2020-12-01 15:00:32,015 - root - INFO - gateway_server.py:283 - 客户端(('192.168.0.97', 26))已成功连接。。
2020-12-01 15:00:51,015 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
2020-12-01 15:01:01,294 - root - ERROR - task_controler.py:159 - 'e5b8f43c-5ff9-4ada-b399-3bd431811be7'
