2020-12-08 14:30:11,471 - root - INFO - main.py:60 - START SERVER
2020-12-08 14:30:12,178 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 14:30:12,235 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 14:30:12,246 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 14:30:12,305 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 14:30:12,331 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 14:30:12,476 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 14:30:12,555 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 14:30:16,430 - root - WARNING - gateway_server.py:106 - equipment (192.168.0.117, 26) is offline
2020-12-08 14:34:02,482 - root - INFO - main.py:60 - START SERVER
2020-12-08 14:34:03,167 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 14:34:03,200 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 14:34:03,231 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 14:34:04,158 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 14:34:04,231 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 14:35:01,233 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 14:41:21,279 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 14:42:24,334 - root - ERROR - task_controler.py:325 - get no user by code 222222222
2020-12-08 14:43:01,915 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 14:45:05,076 - root - INFO - main.py:60 - START SERVER
2020-12-08 14:45:05,813 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 14:45:05,841 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 14:45:05,855 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 14:45:06,495 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 14:45:06,544 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 14:46:02,372 - root - ERROR - task_controler.py:327 - get no user by code 222222222
2020-12-08 14:47:55,300 - root - INFO - main.py:60 - START SERVER
2020-12-08 14:47:56,032 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 14:47:56,067 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 14:47:56,080 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 14:47:56,145 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 14:47:56,183 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 14:48:11,700 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 14:48:30,160 - root - ERROR - task_controler.py:328 - get no user by code 222222222
2020-12-08 14:49:21,983 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 14:50:44,655 - root - INFO - main.py:60 - START SERVER
2020-12-08 14:50:45,334 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 14:50:45,370 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 14:50:45,384 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 14:50:45,843 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 14:50:45,986 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 14:51:22,131 - root - ERROR - task_controler.py:331 - get no user by code 222222222
2020-12-08 14:53:14,458 - root - ERROR - task_controler.py:331 - get no user by code 222222222
2020-12-08 14:57:11,205 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 15:02:22,099 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 15:07:24,249 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:07:24,951 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:07:24,997 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:07:25,011 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:07:25,025 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:07:25,039 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:07:25,123 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:07:25,167 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:07:51,240 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 15:10:46,033 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:10:46,837 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:10:46,859 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:10:46,867 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:10:46,889 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:10:46,929 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:10:46,944 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:10:46,985 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:10:54,162 - root - WARNING - gateway_server.py:106 - equipment (192.168.0.117, 26) is offline
2020-12-08 15:11:27,309 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:11:27,996 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:11:28,028 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:11:28,053 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:11:28,084 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:11:28,122 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:11:28,391 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:11:28,449 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:11:35,464 - root - WARNING - gateway_server.py:106 - equipment (192.168.0.117, 26) is offline
2020-12-08 15:13:51,217 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 15:15:39,568 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:15:40,316 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:15:40,359 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:15:40,389 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:15:40,432 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:15:41,087 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:15:41,145 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:16:08,262 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:16:08,964 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:16:08,992 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:16:09,002 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:16:09,012 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:16:09,047 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:16:09,315 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:16:09,382 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:16:32,645 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:16:33,368 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:16:33,394 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:16:33,406 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:16:33,426 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:16:33,472 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:16:34,085 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:16:34,115 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:16:38,625 - root - WARNING - gateway_server.py:106 - equipment (192.168.0.117, 26) is offline
2020-12-08 15:24:20,889 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:24:21,570 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:24:21,603 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:24:21,629 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:24:21,651 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:24:22,043 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:24:22,094 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:24:53,008 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:24:53,678 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:24:53,729 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:24:53,745 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:24:53,849 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:24:53,945 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:28:05,452 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:28:06,133 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:28:06,165 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:28:06,183 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:28:06,197 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:28:06,244 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:28:06,375 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:28:06,434 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:28:51,277 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 15:29:02,602 - root - ERROR - Object2.py:635 - index out of range
2020-12-08 15:31:30,908 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:31:31,687 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:31:31,714 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:31:31,724 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:31:31,754 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:31:31,783 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:31:32,247 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:31:32,343 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:31:37,147 - root - WARNING - gateway_server.py:106 - equipment (192.168.0.117, 26) is offline
2020-12-08 15:33:24,923 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:33:25,690 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:33:25,722 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:33:25,751 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:33:25,780 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:33:26,228 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:33:26,314 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:38:24,346 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:38:25,125 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:38:25,184 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:38:25,220 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:38:25,879 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:38:26,026 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:40:52,204 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 15:47:22,240 - root - ERROR - Object2.py:62 - 'int' object has no attribute 'hex'
2020-12-08 15:51:51,160 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:51:51,949 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:51:51,990 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:51:52,003 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:51:52,037 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:51:52,065 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:51:52,201 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:51:52,245 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:55:33,682 - root - INFO - main.py:60 - START SERVER
2020-12-08 15:55:34,420 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2020-12-08 15:55:34,451 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:55:34,479 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 23))已成功连接。。online
2020-12-08 15:55:34,497 - root - INFO - gateway_server.py:242 - 服务端(('192.168.0.117', 26))已成功连接。。online
2020-12-08 15:55:35,312 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 23))已成功连接。。online
2020-12-08 15:55:35,450 - root - INFO - gateway_server.py:292 - 客户端(('192.168.0.97', 26))已成功连接。。online
2020-12-08 15:58:51,457 - root - ERROR - task_controler.py:331 - get no user by code 222222222
