2020-12-21 00:00:20,096 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:00:20,211 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:00:20,313 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:00:40,442 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:00:40,550 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:00:40,655 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:01:00,779 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:01:00,883 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:01:00,986 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:01:21,109 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:01:21,211 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:01:21,313 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:01:41,426 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:01:41,528 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:01:41,631 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:02:01,761 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:02:01,867 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:02:01,971 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:02:22,099 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:02:22,205 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:02:22,326 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:02:42,452 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:02:42,556 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:02:42,660 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:03:02,802 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:03:02,920 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:03:03,038 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:03:23,168 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:03:23,270 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:03:23,372 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:03:43,509 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:03:43,615 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:03:43,720 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:04:03,850 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:04:03,951 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:04:04,053 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:04:24,185 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:04:24,292 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:04:24,400 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:04:44,522 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:04:44,623 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:04:44,727 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:05:04,851 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:05:04,955 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:05:05,068 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:05:25,189 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:05:25,290 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:05:25,392 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:05:45,516 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:05:45,619 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:05:45,721 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:06:05,841 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:06:05,959 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:06:06,064 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:06:26,190 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:06:26,296 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:06:26,400 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:06:46,524 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:06:46,626 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:06:46,727 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:07:06,854 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:07:06,961 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:07:07,065 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:07:27,194 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:07:27,306 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:07:27,413 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:07:47,538 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:07:47,640 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:07:47,743 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:08:07,866 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:08:07,971 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:08:08,077 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:08:28,198 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:08:28,302 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:08:28,406 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:08:48,530 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:08:48,632 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:08:48,737 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:09:08,863 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:09:08,970 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:09:09,082 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:09:29,208 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:09:29,318 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:09:29,426 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:09:49,547 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:09:49,651 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:09:49,754 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:10:09,877 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:10:09,980 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:10:10,085 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:10:30,213 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:10:30,317 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:10:30,426 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:10:50,552 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:10:50,656 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:10:50,763 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:11:10,882 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:11:10,985 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:11:11,087 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:11:31,212 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:11:31,315 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:11:31,417 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:11:51,537 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:11:51,650 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:11:51,755 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:12:11,881 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:12:11,987 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:12:12,091 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:12:32,215 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:12:32,318 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:12:32,421 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:12:52,545 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:12:52,648 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:12:52,750 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:13:12,860 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:13:12,965 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:13:13,067 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:13:33,184 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:13:33,288 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:13:33,392 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:13:53,518 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:13:53,621 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:13:53,723 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:14:13,844 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:14:13,948 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:14:14,057 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:14:34,181 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:14:34,288 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:14:34,393 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:14:54,516 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:14:54,621 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:14:54,724 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:15:14,850 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:15:14,961 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:15:15,064 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:15:35,186 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:15:35,290 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:15:35,393 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:15:55,518 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:15:55,621 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:15:55,723 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:16:15,846 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:16:15,951 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:16:16,054 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:16:36,186 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:16:36,291 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:16:36,394 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:16:56,517 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:16:56,619 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:16:56,720 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:17:16,845 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:17:16,948 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:17:17,055 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:17:37,180 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:17:37,283 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:17:37,385 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:17:57,509 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:17:57,614 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:17:57,719 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:18:17,851 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:18:17,959 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:18:18,069 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:18:38,193 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:18:38,296 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:18:38,402 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:18:58,526 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:18:58,630 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:18:58,735 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:19:18,861 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:19:18,966 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:19:19,069 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:19:39,195 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:19:39,298 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:19:39,401 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:19:59,529 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:19:59,632 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:19:59,738 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:20:19,861 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:20:19,966 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:20:20,068 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:20:40,190 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:20:40,292 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:20:40,394 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:21:00,516 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:21:00,619 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:21:00,722 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:21:20,845 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:21:20,948 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:21:21,054 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:21:41,175 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:21:41,278 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:21:41,381 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:22:01,507 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:22:01,609 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:22:01,713 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:22:21,841 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:22:21,944 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:22:22,047 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:22:42,178 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:22:42,282 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:22:42,385 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:23:02,509 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:23:02,613 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:23:02,724 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:23:22,858 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:23:22,964 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:23:23,074 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:23:43,207 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:23:43,313 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:23:43,418 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:24:03,539 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:24:03,645 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:24:03,749 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:24:23,873 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:24:23,980 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:24:24,085 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:24:44,210 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:24:44,313 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:24:44,422 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:25:04,546 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:25:04,648 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:25:04,750 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:25:24,873 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:25:24,978 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:25:25,085 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:25:45,209 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:25:45,314 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:25:45,419 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:26:05,540 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:26:05,642 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:26:05,745 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:26:25,867 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:26:25,969 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:26:26,072 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:26:46,196 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:26:46,307 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:26:46,411 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:27:06,548 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:27:06,651 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:27:06,755 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:27:26,874 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:27:26,978 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:27:27,083 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:27:47,217 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:27:47,325 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:27:47,434 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:28:07,568 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:28:07,670 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:28:07,772 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:28:27,894 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:28:27,999 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:28:28,104 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:28:48,234 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:28:48,337 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:28:48,442 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:29:08,569 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:29:08,672 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:29:08,774 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:29:28,901 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:29:29,010 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:29:29,121 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:29:49,247 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:29:49,348 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:29:49,450 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:30:09,573 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:30:09,676 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:30:09,784 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:30:29,906 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:30:30,010 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:30:30,118 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:30:50,245 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:30:50,347 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:30:50,448 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:31:10,577 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:31:10,681 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:31:10,784 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:31:30,903 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:31:31,008 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:31:31,112 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:31:51,231 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:31:51,332 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:31:51,443 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:32:11,567 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:32:11,670 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:32:11,775 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:32:31,912 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:32:32,016 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:32:32,122 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:32:52,254 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:32:52,365 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:32:52,475 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:33:12,604 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:33:12,710 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:33:12,816 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:33:32,944 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:33:33,048 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:33:33,151 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:33:53,274 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:33:53,376 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:33:53,478 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:34:13,610 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:34:13,711 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:34:13,813 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:34:33,936 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:34:34,040 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:34:34,143 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:34:54,267 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:34:54,371 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:34:54,486 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:35:14,616 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:35:14,724 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:35:14,830 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:35:34,957 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:35:35,061 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:35:35,170 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:35:55,301 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:35:55,410 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:35:55,519 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:36:15,664 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:36:15,766 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:36:15,871 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:36:35,995 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:36:36,105 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:36:36,210 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:36:56,330 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:36:56,432 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:36:56,535 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:37:16,658 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:37:16,761 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:37:16,863 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:37:36,985 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:37:37,087 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:37:37,189 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:37:57,311 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:37:57,417 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:37:57,521 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:38:17,652 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:38:17,760 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:38:17,868 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:38:37,996 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:38:38,101 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:38:38,208 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:38:58,342 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:38:58,445 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:38:58,549 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:39:18,672 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:39:18,776 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:39:18,878 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:39:39,003 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:39:39,108 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:39:39,212 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:39:59,347 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:39:59,450 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:39:59,553 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:40:19,676 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:40:19,779 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:40:19,885 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:40:40,026 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:40:40,134 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:40:40,242 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:41:00,367 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:41:00,473 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:41:00,582 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:41:20,710 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:41:20,814 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:41:20,925 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:41:41,055 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:41:41,164 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:41:41,268 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:42:01,390 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:42:01,494 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:42:01,599 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:42:21,723 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:42:21,825 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:42:21,932 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:42:42,061 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:42:42,175 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:42:42,278 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:43:02,420 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:43:02,539 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:43:02,645 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:43:22,782 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:43:22,889 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:43:22,997 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:43:43,119 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:43:43,222 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:43:43,334 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:44:03,454 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:44:03,558 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:44:03,661 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:44:23,785 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:44:23,887 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:44:23,988 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:44:44,110 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:44:44,214 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:44:44,320 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:45:04,443 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:45:04,548 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:45:04,653 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:45:24,784 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:45:24,894 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:45:24,998 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:45:45,122 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:45:45,225 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:45:45,329 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:46:05,450 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:46:05,551 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:46:05,653 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:46:25,781 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:46:25,886 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:46:25,994 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:46:46,115 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:46:46,223 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:46:46,327 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:47:06,449 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:47:06,551 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:47:06,652 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:47:26,778 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:47:26,887 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:47:26,994 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:47:47,117 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:47:47,223 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:47:47,331 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:48:07,464 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:48:07,574 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:48:07,685 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:48:27,822 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:48:27,935 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:48:28,038 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:48:48,162 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:48:48,265 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:48:48,370 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:49:08,498 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:49:08,608 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:49:08,714 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:49:28,836 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:49:28,938 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:49:29,040 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:49:49,162 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:49:49,269 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:49:49,371 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:50:09,490 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:50:09,592 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:50:09,709 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:50:29,829 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:50:29,938 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:50:30,045 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:50:50,168 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:50:50,273 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:50:50,377 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:51:10,510 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:51:10,623 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:51:10,729 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:51:30,856 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:51:30,959 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:51:31,063 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:51:51,190 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:51:51,297 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:51:51,399 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:52:11,528 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:52:11,634 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:52:11,740 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:52:31,866 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:52:31,978 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:52:32,086 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:52:52,214 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:52:52,317 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:52:52,422 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:53:12,532 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:53:12,638 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:53:12,749 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:53:32,873 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:53:32,976 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:53:33,079 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:53:53,226 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:53:53,341 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:53:53,445 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:54:13,569 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:54:13,673 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:54:13,775 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:54:33,898 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:54:34,000 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:54:34,105 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:54:54,235 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:54:54,346 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:54:54,450 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:55:14,584 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:55:14,691 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:55:14,796 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:55:34,921 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:55:35,024 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:55:35,134 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:55:55,255 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:55:55,358 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:55:55,473 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:56:15,599 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:56:15,703 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:56:15,806 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:56:35,931 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:56:36,034 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:56:36,137 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:56:56,259 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:56:56,361 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:56:56,462 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:57:16,587 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:57:16,702 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:57:16,807 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:57:36,930 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:57:37,032 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:57:37,133 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:57:57,256 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:57:57,360 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:57:57,464 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:58:17,587 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:58:17,690 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:58:17,795 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:58:37,919 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:58:38,023 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:58:38,127 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:58:58,253 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:58:58,358 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:58:58,463 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:59:18,585 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:59:18,690 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:59:18,794 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:59:38,919 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:59:39,023 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:59:39,126 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 00:59:59,251 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 00:59:59,355 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 00:59:59,457 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:00:19,585 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:00:19,689 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:00:19,791 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:00:39,923 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:00:40,052 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:00:40,155 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:01:00,278 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:01:00,381 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:01:00,485 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:01:20,610 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:01:20,712 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:01:20,813 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:01:40,940 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:01:41,044 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:01:41,148 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:02:01,273 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:02:01,377 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:02:01,484 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:02:21,609 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:02:21,721 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:02:21,829 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:02:41,950 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:02:42,052 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:02:42,154 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:03:02,283 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:03:02,386 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:03:02,489 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:03:22,613 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:03:22,718 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:03:22,821 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:03:42,946 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:03:43,049 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:03:43,152 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:04:03,277 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:04:03,385 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:04:03,489 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:04:23,611 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:04:23,714 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:04:23,824 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:04:43,964 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:04:44,070 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:04:44,173 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:05:04,296 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:05:04,398 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:05:04,499 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:05:24,623 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:05:24,725 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:05:24,829 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:05:44,967 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:05:45,069 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:05:45,174 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:06:05,298 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:06:05,402 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:06:05,504 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:06:25,633 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:06:25,749 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:06:25,856 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:06:45,977 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:06:46,081 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:06:46,183 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:07:06,309 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:07:06,412 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:07:06,516 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:07:26,640 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:07:26,743 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:07:26,846 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:07:46,968 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:07:47,071 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:07:47,174 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:08:07,300 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:08:07,402 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:08:07,509 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:08:27,633 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:08:27,737 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:08:27,844 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:08:47,969 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:08:48,072 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:08:48,179 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:09:08,307 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:09:08,411 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:09:08,512 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:09:28,637 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:09:28,744 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:09:28,847 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:09:48,969 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:09:49,070 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:09:49,171 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:10:09,292 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:10:09,396 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:10:09,498 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:10:29,619 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:10:29,720 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:10:29,822 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:10:49,944 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:10:50,047 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:10:50,150 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:11:10,284 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:11:10,391 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:11:10,505 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:11:30,629 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:11:30,739 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:11:30,840 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:11:50,955 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:11:51,063 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:11:51,169 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:12:11,286 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:12:11,391 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:12:11,494 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:12:31,621 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:12:31,726 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:12:31,829 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:12:51,952 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:12:52,053 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:12:52,156 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:13:12,279 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:13:12,381 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:13:12,483 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:13:32,615 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:13:32,718 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:13:32,819 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:13:52,941 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:13:53,046 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:13:53,155 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:14:13,292 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:14:13,394 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:14:13,497 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:14:33,624 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:14:33,738 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:14:33,840 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:14:53,967 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:14:54,074 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:14:54,177 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:15:14,299 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:15:14,401 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:15:14,502 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:15:34,615 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:15:34,718 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:15:34,820 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:15:54,942 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:15:55,045 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:15:55,147 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:16:15,286 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:16:15,387 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:16:15,500 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:16:35,632 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:16:35,737 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:16:35,846 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:16:55,970 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:16:56,073 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:16:56,178 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:17:16,303 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:17:16,407 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:17:16,510 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:17:36,639 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:17:36,745 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:17:36,849 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:17:56,973 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:17:57,080 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:17:57,189 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:18:17,322 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:18:17,427 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:18:17,530 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:18:37,653 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:18:37,761 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:18:37,862 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:18:57,988 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:18:58,091 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:18:58,196 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:19:18,324 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:19:18,429 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:19:18,532 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:19:38,657 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:19:38,763 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:19:38,869 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:19:58,992 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:19:59,094 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:19:59,194 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:20:19,314 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:20:19,419 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:20:19,524 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:20:39,648 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:20:39,751 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:20:39,853 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:20:59,980 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:21:00,082 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:21:00,185 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:21:20,310 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:21:20,413 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:21:20,515 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:21:40,641 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:21:40,743 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:21:40,847 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:22:00,981 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:22:01,083 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:22:01,190 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:22:21,317 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:22:21,420 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:22:21,527 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:22:41,655 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:22:41,762 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:22:41,872 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:23:02,002 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:23:02,106 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:23:02,209 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:23:22,339 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:23:22,442 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:23:22,547 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:23:42,668 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:23:42,770 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:23:42,872 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:24:02,994 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:24:03,102 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:24:03,209 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:24:23,341 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:24:23,452 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:24:23,558 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:24:43,680 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:24:43,782 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:24:43,887 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:25:04,011 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:25:04,114 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:25:04,217 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:25:24,342 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:25:24,445 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:25:24,548 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:25:44,685 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:25:44,801 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:25:44,912 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:26:05,043 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:26:05,145 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:26:05,248 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:26:25,376 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:26:25,478 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:26:25,587 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:26:45,716 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:26:45,818 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:26:45,923 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:27:06,065 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:27:06,168 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:27:06,271 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:27:26,398 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:27:26,501 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:27:26,602 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:27:46,723 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:27:46,825 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:27:46,926 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:28:07,050 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:28:07,154 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:28:07,256 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:28:27,389 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:28:27,500 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:28:27,605 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:28:47,727 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:28:47,828 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:28:47,937 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:29:08,065 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:29:08,169 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:29:08,271 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:29:28,401 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:29:28,506 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:29:28,611 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:29:48,737 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:29:48,840 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:29:48,947 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:30:09,068 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:30:09,169 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:30:09,270 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:30:29,397 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:30:29,499 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:30:29,603 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:30:49,729 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:30:49,838 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:30:49,941 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:31:10,064 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:31:10,169 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:31:10,272 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:31:30,399 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:31:30,502 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:31:30,603 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:31:50,746 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:31:50,861 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:31:50,963 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:32:11,086 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:32:11,194 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:32:11,300 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:32:31,421 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:32:31,534 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:32:31,638 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:32:51,761 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:32:51,865 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:32:51,971 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:33:12,115 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:33:12,219 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:33:12,325 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:33:32,451 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:33:32,554 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:33:32,660 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:33:52,791 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:33:52,903 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:33:53,009 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:34:13,131 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:34:13,235 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:34:13,350 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:34:33,480 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:34:33,586 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:34:33,689 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:34:53,818 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:34:53,924 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:34:54,032 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:35:14,173 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:35:14,276 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:35:14,379 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:35:34,503 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:35:34,604 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:35:34,706 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:35:54,830 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:35:54,932 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:35:55,041 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:36:15,168 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:36:15,272 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:36:15,376 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:36:35,499 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:36:35,602 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:36:35,707 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:36:55,830 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:36:55,933 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:36:56,034 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:37:16,159 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:37:16,268 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:37:16,377 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:37:36,495 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:37:36,598 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:37:36,701 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:37:56,825 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:37:56,933 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:37:57,041 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:38:17,166 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:38:17,275 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:38:17,385 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:38:37,511 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:38:37,616 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:38:37,718 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:38:57,849 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:38:57,954 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:38:58,073 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:39:18,205 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:39:18,312 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:39:18,428 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:39:38,554 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:39:38,657 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:39:38,769 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:39:58,904 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:39:59,014 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:39:59,124 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:40:19,258 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:40:19,360 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:40:19,462 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:40:39,587 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:40:39,691 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:40:39,794 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:40:59,918 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:41:00,019 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:41:00,121 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:41:20,270 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:41:20,373 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:41:20,480 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:41:40,613 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:41:40,721 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:41:40,836 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:42:00,959 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:42:01,062 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:42:01,169 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:42:21,297 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:42:21,400 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:42:21,505 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:42:41,636 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:42:41,751 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:42:41,860 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:43:01,976 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:43:02,082 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:43:02,185 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:43:22,316 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:43:22,427 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:43:22,541 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:43:42,666 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:43:42,769 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:43:42,877 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:44:03,016 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:44:03,120 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:44:03,222 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:44:23,343 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:44:23,448 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:44:23,550 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:44:43,676 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:44:43,785 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:44:43,893 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:45:04,022 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:45:04,140 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:45:04,256 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:45:24,385 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:45:24,495 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:45:24,610 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:45:44,735 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:45:44,837 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:45:44,940 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:46:05,068 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:46:05,171 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:46:05,274 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-21 01:46:25,396 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-21 01:46:25,499 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-21 01:46:25,602 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
