2020-11-21 01:53:12,416 - root - INFO - main.py:43 - START SERVER
2020-11-21 01:53:12,449 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 11:49:19,973 - root - INFO - main.py:43 - START SERVER
2020-11-21 11:49:20,045 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 11:58:36,748 - root - INFO - main.py:43 - START SERVER
2020-11-21 11:58:36,767 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 11:58:51,908 - root - ERROR - gateway_server.py:234 - 'dict' object has no attribute 'target'
2020-11-21 12:10:57,796 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:10:57,817 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:11:10,999 - root - WARNING - task_controler.py:95 - decoding to str: need a bytes-like object, dict found
2020-11-21 12:17:30,299 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:17:30,315 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:17:38,023 - root - ERROR - gateway_server.py:234 - 'dict' object has no attribute 'target'
2020-11-21 12:20:33,330 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:20:33,347 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:20:42,667 - root - WARNING - task_controler.py:98 - too many values to unpack (expected 2)
2020-11-21 12:22:32,454 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:22:32,469 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:22:43,997 - root - WARNING - task_controler.py:100 - too many values to unpack (expected 2)
2020-11-21 12:23:31,347 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:23:31,361 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:23:38,183 - root - WARNING - task_controler.py:100 - 'TransferPackage' object does not support item assignment
2020-11-21 12:29:24,548 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:29:24,582 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:29:37,002 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:29:37,021 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:30:13,248 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:30:13,264 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:31:05,265 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:31:05,283 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:41:13,378 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:41:13,395 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:42:42,527 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:42:42,541 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:43:17,721 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:43:17,732 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:47:56,470 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:47:56,485 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:48:25,464 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:48:25,486 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:48:53,442 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:48:53,457 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:51:44,413 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:51:44,432 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:53:08,675 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:53:08,690 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:55:58,528 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:55:58,546 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 12:57:07,970 - root - INFO - main.py:43 - START SERVER
2020-11-21 12:57:07,985 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 13:05:08,612 - root - INFO - main.py:43 - START SERVER
2020-11-21 13:05:08,631 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 13:07:23,649 - root - INFO - main.py:43 - START SERVER
2020-11-21 13:07:23,664 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 13:11:52,969 - root - INFO - main.py:43 - START SERVER
2020-11-21 13:11:52,987 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 13:15:18,721 - root - INFO - main.py:43 - START SERVER
2020-11-21 13:15:18,737 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 16:55:21,555 - root - INFO - main.py:43 - START SERVER
2020-11-21 16:55:21,603 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 17:06:20,636 - root - INFO - main.py:43 - START SERVER
2020-11-21 17:06:20,654 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
2020-11-21 17:07:50,271 - root - INFO - gateway_server.py:178 - 客户端(('192.168.8.221', 23))已成功连接。。
2020-11-21 18:54:44,467 - root - INFO - main.py:43 - START SERVER
2020-11-21 18:54:44,479 - root - INFO - gateway_server.py:47 - There is None registered server for connecting!
2020-11-21 21:42:30,724 - root - INFO - main.py:43 - START SERVER
2020-11-21 21:42:30,747 - root - INFO - gateway_server.py:47 - There is None registered server for connecting!
2020-11-21 21:44:28,312 - root - INFO - main.py:45 - START SERVER
2020-11-21 21:44:28,327 - root - ERROR - gateway_server.py:66 - 'list' object has no attribute 'items'
2020-11-21 21:46:01,003 - root - INFO - main.py:45 - START SERVER
2020-11-21 21:46:01,018 - root - INFO - gateway_server.py:135 - 客户端(('192.168.8.221', 4370))已成功连接。。
