2021-01-14 16:18:03,384 - root - INFO - main.py:59 - START SERVER
2021-01-14 16:18:53,813 - root - INFO - main.py:59 - START SERVER
2021-01-14 16:18:53,921 - root - INFO - gateway_server.py:188 - 服务端(('192.168.0.101', 8000))已成功连接。。online
2021-01-14 16:18:54,089 - root - INFO - base_adapter.py:74 - SDK初始化成功
2021-01-14 16:18:54,387 - root - ERROR - base_adapter.py:67 - 没有找到接口！
2021-01-14 16:18:54,391 - root - ERROR - base_adapter.py:219 - NET_DVR_SetDVRMessageCallBack_V31 初始化SDK失败: the error code is 0
2021-01-14 16:18:54,489 - root - INFO - gateway_server.py:188 - 服务端(('192.168.0.201', 4370))已成功连接。。online
2021-01-14 16:18:54,595 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.118', 23)
2021-01-14 16:18:54,598 - root - INFO - gateway_server.py:188 - 服务端(('192.168.0.117', 26))已成功连接。。online
2021-01-14 16:18:54,611 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.117', 23)
2021-01-14 16:18:54,623 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.117', 23)
2021-01-14 16:18:54,758 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.118', 23)
2021-01-14 16:18:55,428 - root - INFO - gateway_server.py:255 - 客户端(('192.168.0.97', 23))已成功连接。。online
2021-01-14 16:18:55,624 - root - INFO - gateway_server.py:255 - 客户端(('192.168.0.97', 26))已成功连接。。online
2021-01-14 16:18:55,627 - root - INFO - gateway_server.py:259 - 客户端(('192.168.0.117', 23))连接创建线程失败。。
2021-01-14 16:19:14,858 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.117', 23)
2021-01-14 16:19:14,991 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.118', 23)
2021-01-14 16:19:35,143 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.117', 23)
2021-01-14 16:19:35,345 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.118', 23)
2021-01-14 16:19:55,509 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.117', 23)
2021-01-14 16:19:55,671 - root - WARNING - gateway_server.py:196 - fail to connect to server ('192.168.0.118', 23)
2021-01-14 16:20:09,944 - root - WARNING - gateway_server.py:105 - equipment (192.168.0.117, 26) is offline
