2020-12-20 04:07:21,744 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:07:22,089 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:07:22,197 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:07:22,299 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:07:22,402 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:07:22,418 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:07:22,523 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:07:22,629 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:07:22,734 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:07:42,766 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:07:42,877 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:07:42,979 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:07:43,082 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:08:03,108 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:08:03,210 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:08:03,312 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:08:03,416 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:08:23,464 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:08:23,565 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:08:23,669 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:08:23,785 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:08:43,819 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:08:43,926 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:08:44,033 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:08:44,137 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:09:04,169 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:09:04,274 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:09:04,378 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:09:04,481 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:09:24,506 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:09:24,613 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:09:24,715 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:09:24,823 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:09:44,863 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:09:44,972 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:09:45,080 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:09:45,190 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:10:01,685 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:10:01,967 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:10:02,077 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:10:02,179 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:10:02,281 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:10:02,303 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:10:02,406 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:10:02,508 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:10:02,612 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:10:22,647 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:10:22,757 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:10:22,859 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:10:22,961 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:10:43,000 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:10:43,102 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:10:43,204 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:10:43,305 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:11:03,335 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:11:03,440 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:11:03,548 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:11:03,657 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:11:23,689 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:11:23,803 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:11:23,916 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:11:24,028 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:11:44,093 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:11:44,206 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:11:44,318 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:11:44,430 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:12:04,465 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:12:04,575 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:12:04,685 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:12:04,795 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:12:24,827 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:12:24,931 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:12:25,033 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:12:25,138 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:12:45,167 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:12:45,268 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:12:45,371 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:12:45,491 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:13:05,524 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:13:05,625 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:13:05,729 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:13:05,840 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:13:25,880 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.8.172', 8000)
2020-12-20 04:13:25,986 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:13:26,089 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:13:26,193 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:13:46,940 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:13:47,231 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:13:47,263 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,263 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:47,264 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:13:47,269 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,269 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:47,272 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,272 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:47,356 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:13:47,458 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:13:47,560 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:13:47,595 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,595 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:13:47,599 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,599 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:47,603 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,603 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:47,631 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,632 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:13:47,669 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:13:47,800 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:13:47,878 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:13:47,893 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,893 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:47,894 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:13:47,906 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,909 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:47,923 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:47,924 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:48,023 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:13:48,950 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:48,950 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:48,954 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:48,954 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:48,957 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:48,957 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:13:48,980 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:13:48,980 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:08,218 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:14:08,362 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:14:08,378 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:14:08,382 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:08,382 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:08,382 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:14:08,384 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:08,384 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:08,412 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:08,412 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:08,451 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:08,451 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:14:08,478 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:08,479 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:08,508 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:08,514 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:08,554 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:14:08,631 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:08,632 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:14:20,810 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:14:21,752 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:14:22,699 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:14:28,751 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:14:29,098 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:14:29,136 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:14:29,253 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:14:29,272 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:29,272 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:29,273 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:14:29,316 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:29,316 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:29,327 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:29,328 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:29,419 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:29,419 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:14:29,445 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:29,445 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:29,458 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:29,458 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:29,509 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:29,509 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:14:49,462 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:14:49,603 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:14:49,628 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:14:49,840 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:49,841 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:49,865 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:14:49,864 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:14:49,877 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:49,878 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:49,880 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:49,881 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:50,032 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:50,032 - root - INFO - base_adapter.py:59 - 执行成功,返回值：4
2020-12-20 04:14:50,197 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:50,203 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:50,388 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:50,394 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:14:50,784 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:50,785 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:14:50,836 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:14:50,837 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:14:50,838 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:15:06,297 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:15:07,296 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:15:08,312 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:15:09,412 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:15:10,267 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:15:10,710 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:15:10,873 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:15:11,035 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,035 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:11,036 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:15:11,073 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,073 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:11,107 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,107 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:11,209 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,210 - root - INFO - base_adapter.py:59 - 执行成功,返回值：5
2020-12-20 04:15:11,233 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:15:11,247 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,247 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:11,336 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,336 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:11,516 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,517 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:15:11,572 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:11,573 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:15:11,573 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:15:31,884 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:15:32,109 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:15:32,765 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:15:32,847 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:32,859 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:32,930 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:15:32,929 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:15:32,959 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:32,996 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:33,026 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:33,026 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:33,146 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:33,146 - root - INFO - base_adapter.py:59 - 执行成功,返回值：6
2020-12-20 04:15:33,208 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:33,215 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:33,302 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:33,302 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:33,443 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:33,443 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:15:33,644 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:33,645 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:15:33,645 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:15:53,360 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:15:53,733 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:15:53,865 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:15:54,271 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:15:54,486 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:54,486 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:54,486 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:15:54,562 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:54,562 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:54,615 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:54,615 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:54,660 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:54,660 - root - INFO - base_adapter.py:59 - 执行成功,返回值：7
2020-12-20 04:15:54,804 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:54,804 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:54,962 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:54,963 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:15:56,255 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:56,256 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:15:56,673 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:15:56,673 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:15:56,673 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:16:14,639 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:16:15,068 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:16:15,143 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:16:15,465 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:15,466 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:15,466 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:16:15,488 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:15,493 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:15,581 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:16:15,588 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:15,588 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:15,666 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:15,666 - root - INFO - base_adapter.py:59 - 执行成功,返回值：8
2020-12-20 04:16:16,424 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:16,424 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:17,725 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:17,725 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:17,948 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:18,047 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:16:18,101 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:18,102 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:16:18,102 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:16:35,941 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:16:36,332 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:16:36,807 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:16:37,144 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:37,210 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:37,210 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:16:37,405 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:16:37,498 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:37,509 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:37,539 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:37,540 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:37,762 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:37,763 - root - INFO - base_adapter.py:59 - 执行成功,返回值：9
2020-12-20 04:16:37,817 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:37,818 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:37,871 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:37,871 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:38,152 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:38,159 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:16:38,432 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:38,433 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:16:38,433 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:16:58,070 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:16:58,561 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:16:58,688 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:16:58,927 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:16:59,410 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:59,416 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:59,416 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:16:59,423 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:59,424 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:59,559 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:59,559 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:16:59,667 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:59,667 - root - INFO - base_adapter.py:59 - 执行成功,返回值：10
2020-12-20 04:16:59,783 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:16:59,951 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:17:00,943 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:17:00,943 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:17:01,029 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:17:01,035 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:17:01,137 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:17:01,138 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:17:01,138 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:21:22,001 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:21:22,234 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:21:22,322 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,322 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,322 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:21:22,326 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,326 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,329 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,329 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,343 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:21:22,445 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:21:22,512 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,512 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:21:22,515 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,516 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,517 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,518 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,534 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,535 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:21:22,561 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:21:22,581 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:21:22,619 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,619 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,619 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:21:22,621 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,621 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,624 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:22,624 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:22,703 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:21:22,819 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:21:22,927 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:21:23,662 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:23,662 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:23,665 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:23,665 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:23,670 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:23,671 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:23,690 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:23,709 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:42,953 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:21:42,957 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:42,958 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:42,958 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:21:42,986 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:42,986 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:43,026 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:43,026 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:43,098 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:21:43,147 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:43,147 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:21:43,153 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:43,153 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:43,176 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:43,201 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:21:43,229 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:21:43,229 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:21:43,272 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:21:43,384 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:22:03,490 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:03,497 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:03,497 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:22:03,498 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:22:03,530 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:03,530 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:03,540 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:03,540 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:03,583 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:03,594 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:22:03,632 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:03,633 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:03,646 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:03,698 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:03,735 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:22:03,864 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:03,864 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:22:04,068 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:22:04,330 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:22:24,563 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:22:24,769 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:22:24,951 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:22:24,969 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:24,969 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:24,969 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:22:24,977 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:24,977 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:24,990 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:24,991 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:25,033 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:25,034 - root - INFO - base_adapter.py:59 - 执行成功,返回值：4
2020-12-20 04:22:25,079 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:25,080 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:25,122 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:25,123 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:25,229 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:25,230 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:22:25,248 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:22:25,323 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:25,324 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:22:25,324 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:22:45,489 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:22:45,590 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:45,596 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:45,596 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:22:45,605 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:45,622 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:45,665 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:45,698 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:45,709 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:22:45,804 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:45,804 - root - INFO - base_adapter.py:59 - 执行成功,返回值：5
2020-12-20 04:22:45,879 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:45,885 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:45,918 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:45,918 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:22:45,978 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:46,084 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:22:46,104 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:22:46,109 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:22:46,110 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:22:46,117 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:22:46,859 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:23:07,028 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:23:07,385 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:23:07,537 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,544 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:07,544 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:23:07,692 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,692 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:07,702 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,709 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:07,734 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:23:07,833 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,834 - root - INFO - base_adapter.py:59 - 执行成功,返回值：6
2020-12-20 04:23:07,904 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,904 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:07,906 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,912 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:07,956 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,956 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:23:07,965 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:07,971 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:23:07,977 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:23:08,142 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:23:28,226 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:23:28,579 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:23:28,636 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:28,636 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:28,636 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:23:28,637 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:28,638 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:28,755 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:23:28,786 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:28,786 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:28,896 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:28,897 - root - INFO - base_adapter.py:59 - 执行成功,返回值：7
2020-12-20 04:23:28,939 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:28,945 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:29,060 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:23:29,144 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:29,144 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:29,525 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:29,527 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:23:29,912 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:29,913 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:23:29,913 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:23:49,650 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:23:49,899 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:49,905 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:49,911 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:23:49,928 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:23:50,113 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:50,113 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:50,304 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:50,371 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:50,485 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:50,500 - root - INFO - base_adapter.py:59 - 执行成功,返回值：8
2020-12-20 04:23:50,692 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:23:51,172 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:23:51,242 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:51,242 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:51,305 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:51,311 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:23:51,765 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:51,771 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:23:51,982 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:23:51,982 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:23:51,982 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:24:11,704 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:24:11,914 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:11,914 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:11,914 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:24:11,950 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:24:12,159 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:12,397 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:24:12,587 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:12,690 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:12,690 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:12,825 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:24:12,897 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:12,897 - root - INFO - base_adapter.py:59 - 执行成功,返回值：9
2020-12-20 04:24:13,026 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:13,026 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:13,826 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:13,827 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:14,264 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:14,276 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:24:14,739 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:14,740 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:24:14,740 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:24:26,190 - root - ERROR - task_controler.py:465 - get no user by code 1
2020-12-20 04:24:26,691 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:26,691 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:24:27,102 - root - ERROR - task_controler.py:465 - get no user by code 1
2020-12-20 04:24:27,193 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:27,194 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:28,069 - root - ERROR - task_controler.py:465 - get no user by code 1
2020-12-20 04:24:29,136 - root - WARNING - gateway_server.py:106 - equipment (192.168.8.172, 8000) is offline
2020-12-20 04:24:29,231 - root - ERROR - task_controler.py:465 - get no user by code 1
2020-12-20 04:24:33,250 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:24:33,627 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:24:33,757 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:33,865 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:33,876 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:24:33,895 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:33,896 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:34,024 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:24:34,033 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:34,208 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:34,344 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:34,344 - root - INFO - base_adapter.py:59 - 执行成功,返回值：9
2020-12-20 04:24:34,864 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:24:35,612 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:35,613 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:36,580 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:36,580 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:36,733 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:36,733 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:24:36,742 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:36,748 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:24:36,749 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:24:55,280 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:24:55,899 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:24:56,049 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:56,049 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:56,049 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:24:56,059 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:56,059 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:56,145 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:56,145 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:56,195 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:24:56,468 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:56,468 - root - INFO - base_adapter.py:59 - 执行成功,返回值：10
2020-12-20 04:24:56,791 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:24:57,552 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:57,552 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:58,151 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:58,152 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:24:58,337 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:58,338 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:24:58,411 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:24:58,412 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:24:58,412 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:25:21,406 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:25:21,699 - root - INFO - gateway_server.py:246 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:25:21,761 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:21,762 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:21,762 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:25:21,765 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:21,765 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:21,767 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:21,768 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:21,835 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:25:21,938 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:25:22,040 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:25:22,144 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:25:22,156 - root - INFO - gateway_server.py:246 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:25:22,258 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:25:22,286 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:22,287 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:22,287 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:25:22,289 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:22,289 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:22,291 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:22,294 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:22,326 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:22,326 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:25:22,329 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:22,330 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:22,337 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:22,338 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:22,361 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:25:23,335 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:23,336 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:25:23,363 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:23,363 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:23,373 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:23,373 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:23,381 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:23,381 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:23,415 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:23,415 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:42,556 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:25:42,638 - root - INFO - gateway_server.py:246 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:25:42,695 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:42,695 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:42,695 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:25:42,707 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:42,725 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:42,745 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:42,745 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:42,767 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:25:42,808 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:42,808 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:25:42,851 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:42,878 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:42,911 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:42,912 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:25:42,915 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:25:42,930 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:25:42,930 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:26:03,097 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:26:03,225 - root - INFO - gateway_server.py:246 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:26:03,333 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:26:03,339 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:26:03,340 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:26:03,341 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:26:03,341 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:26:03,344 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:26:03,344 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:26:03,367 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:26:03,368 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:26:03,368 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:26:03,387 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:26:03,388 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:26:03,426 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:26:03,426 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:26:03,471 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:26:03,471 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:26:03,692 - root - WARNING - gateway_server.py:254 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:28:34,992 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:28:35,206 - root - INFO - gateway_server.py:247 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:28:35,253 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,253 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,253 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:28:35,255 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,256 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,258 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,258 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,331 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:28:35,434 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:28:35,510 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,510 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:28:35,516 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,516 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,519 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,519 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,536 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:28:35,567 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,567 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:28:35,641 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:28:35,744 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:28:35,747 - root - INFO - gateway_server.py:247 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:28:35,766 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,766 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,766 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:28:35,768 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,768 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,769 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:35,769 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:35,850 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:28:36,793 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:36,793 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:36,797 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:36,797 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:36,801 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:36,802 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:36,825 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:36,825 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:55,974 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:28:56,080 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:28:56,086 - root - INFO - gateway_server.py:247 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:28:56,125 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:56,127 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:56,127 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:28:56,130 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:56,131 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:56,134 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:56,134 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:56,183 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:56,183 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:28:56,185 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:56,186 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:56,189 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:56,189 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:28:56,198 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:28:56,205 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:28:56,205 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:29:16,326 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:29:16,448 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:29:16,472 - root - INFO - gateway_server.py:247 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:29:16,482 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:16,482 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:16,482 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:29:16,485 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:16,486 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:16,491 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:16,491 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:16,521 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:16,522 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:29:16,526 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:16,526 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:16,537 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:16,538 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:16,565 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:16,566 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:29:16,584 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:29:36,716 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:29:36,832 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:29:36,855 - root - INFO - gateway_server.py:247 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:29:36,858 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,858 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:36,858 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:29:36,859 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,860 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:36,882 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,882 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:36,914 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,915 - root - INFO - base_adapter.py:59 - 执行成功,返回值：4
2020-12-20 04:29:36,918 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,918 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:36,919 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,919 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:29:36,956 - root - WARNING - gateway_server.py:255 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:29:36,962 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,962 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:29:36,971 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:29:36,971 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:29:36,971 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:34:51,946 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:34:52,157 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:34:52,207 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,208 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,208 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:34:52,215 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,215 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,218 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,218 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,293 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:34:52,397 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:34:52,452 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,452 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:34:52,456 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,457 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,463 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,463 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,485 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,485 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:34:52,499 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:34:52,609 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:34:52,611 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:34:52,617 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,617 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,618 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:34:52,621 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,621 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,623 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:52,624 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:52,717 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:34:52,824 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:34:53,670 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:53,670 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:53,676 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:53,677 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:53,678 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:53,678 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:34:53,699 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:34:53,700 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:12,956 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:35:12,969 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:35:12,995 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:12,996 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:12,996 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:35:13,000 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:13,001 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:13,005 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:13,005 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:13,039 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:13,039 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:35:13,041 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:13,041 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:13,043 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:13,043 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:13,060 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:13,061 - root - INFO - base_adapter.py:59 - 执行成功,返回值：2
2020-12-20 04:35:13,085 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:35:13,192 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:35:33,324 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:35:33,327 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:35:33,366 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:33,367 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:33,367 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:35:33,370 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:33,370 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:33,373 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:33,373 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:33,411 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:33,415 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:35:33,419 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:33,419 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:33,422 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:33,422 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:33,429 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:35:33,445 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:33,445 - root - INFO - base_adapter.py:59 - 执行成功,返回值：3
2020-12-20 04:35:33,531 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:35:53,661 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:35:53,667 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:35:53,675 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,676 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:53,676 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:35:53,678 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,678 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:53,686 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,687 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:53,729 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,729 - root - INFO - base_adapter.py:59 - 执行成功,返回值：4
2020-12-20 04:35:53,736 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,736 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:53,739 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,739 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:35:53,764 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,765 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:35:53,769 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:35:53,770 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:35:53,770 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:35:53,772 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:35:53,876 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:36:14,014 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:36:14,043 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:36:14,049 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,049 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:14,049 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:36:14,057 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,058 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:14,060 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,060 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:14,111 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,112 - root - INFO - base_adapter.py:59 - 执行成功,返回值：5
2020-12-20 04:36:14,116 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,116 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:14,119 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,120 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:14,143 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,143 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:36:14,145 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:14,145 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:36:14,145 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:36:14,163 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:36:14,287 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:36:34,419 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:36:34,432 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:36:34,439 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,439 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:34,439 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:36:34,451 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,451 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:34,456 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,456 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:34,510 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,511 - root - INFO - base_adapter.py:59 - 执行成功,返回值：6
2020-12-20 04:36:34,514 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,514 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:34,519 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,519 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:34,537 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:36:34,567 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,567 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:36:34,569 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:34,569 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:36:34,569 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:36:34,639 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:36:54,770 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:36:54,785 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:36:54,796 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,796 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:54,796 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:36:54,799 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,800 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:54,803 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,803 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:54,827 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,827 - root - INFO - base_adapter.py:59 - 执行成功,返回值：7
2020-12-20 04:36:54,831 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,831 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:54,836 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,836 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:36:54,850 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,850 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:36:54,853 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:36:54,853 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:36:54,853 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:36:54,890 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:36:54,993 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:37:15,120 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:37:15,133 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,135 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:37:15,137 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:15,146 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:37:15,148 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,148 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:15,152 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,153 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:15,206 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,206 - root - INFO - base_adapter.py:59 - 执行成功,返回值：8
2020-12-20 04:37:15,208 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,208 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:15,210 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,211 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:15,223 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,223 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:37:15,225 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:15,225 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:37:15,225 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:37:15,251 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:37:15,358 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:37:35,489 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:37:35,493 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:37:35,521 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,522 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:35,522 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:37:35,526 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,526 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:35,529 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,529 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:35,561 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,561 - root - INFO - base_adapter.py:59 - 执行成功,返回值：9
2020-12-20 04:37:35,565 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,565 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:35,568 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,568 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:35,606 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:37:35,608 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,609 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:37:35,612 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:35,612 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:37:35,613 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:37:35,715 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:37:55,841 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:37:55,848 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:37:55,866 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,867 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:55,867 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:37:55,869 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,869 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:55,871 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,872 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:55,917 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,918 - root - INFO - base_adapter.py:59 - 执行成功,返回值：10
2020-12-20 04:37:55,921 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,921 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:55,930 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,931 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:37:55,950 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:37:55,957 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,957 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:37:55,959 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:37:55,960 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:37:55,960 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:37:56,056 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:38:16,183 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:38:16,187 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:38:16,194 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,195 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:16,195 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:38:16,198 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,198 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:16,201 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,201 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:16,253 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,253 - root - INFO - base_adapter.py:59 - 执行成功,返回值：11
2020-12-20 04:38:16,256 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,256 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:16,260 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,260 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:16,279 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,280 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:38:16,283 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:16,283 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:38:16,284 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:38:16,295 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:38:16,399 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:38:36,529 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:38:36,535 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:38:36,540 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,541 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:36,541 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:38:36,542 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,543 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:36,546 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,546 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:36,598 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,600 - root - INFO - base_adapter.py:59 - 执行成功,返回值：12
2020-12-20 04:38:36,603 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,604 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:36,608 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,609 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:36,627 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,627 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:38:36,629 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:36,639 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:38:36,639 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:38:36,640 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:38:36,745 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:38:56,873 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:38:56,878 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:38:56,887 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,887 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:56,887 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:38:56,895 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,895 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:56,898 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,899 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:56,943 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,943 - root - INFO - base_adapter.py:59 - 执行成功,返回值：13
2020-12-20 04:38:56,946 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,946 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:56,949 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,950 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:38:56,967 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,967 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:38:56,971 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:38:56,971 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:38:56,971 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:38:56,984 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:38:57,089 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:39:17,216 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:39:17,228 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:39:17,235 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,236 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:17,236 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:39:17,239 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,240 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:17,243 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,244 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:17,279 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,279 - root - INFO - base_adapter.py:59 - 执行成功,返回值：14
2020-12-20 04:39:17,283 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,284 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:17,286 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,286 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:17,315 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,316 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:39:17,319 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:17,319 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:39:17,319 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:39:17,335 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:39:17,439 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:39:37,565 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:39:37,572 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:39:37,590 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,590 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:37,590 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:39:37,592 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,593 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:37,596 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,596 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:37,669 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,670 - root - INFO - base_adapter.py:59 - 执行成功,返回值：15
2020-12-20 04:39:37,673 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,673 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:37,676 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,676 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:37,681 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:39:37,701 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,701 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:39:37,704 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:37,705 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:39:37,705 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:39:37,784 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:39:57,917 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:39:57,919 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:39:57,923 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,925 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:57,925 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:39:57,928 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,928 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:57,930 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,933 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:57,966 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,966 - root - INFO - base_adapter.py:59 - 执行成功,返回值：16
2020-12-20 04:39:57,969 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,969 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:57,970 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,973 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:39:57,995 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,995 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:39:57,997 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:39:57,997 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:39:57,998 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:39:58,025 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:39:58,127 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:40:18,255 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:40:18,277 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:40:18,289 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,298 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:18,299 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:40:18,303 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,304 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:18,308 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,311 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:18,346 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,347 - root - INFO - base_adapter.py:59 - 执行成功,返回值：17
2020-12-20 04:40:18,349 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,350 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:18,352 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,352 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:18,376 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,376 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:40:18,380 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:18,380 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:40:18,380 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:40:18,397 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:40:18,504 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:40:38,641 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:40:38,664 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:40:38,674 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,675 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:38,675 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:40:38,676 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,677 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:38,679 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,679 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:38,714 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,714 - root - INFO - base_adapter.py:59 - 执行成功,返回值：18
2020-12-20 04:40:38,716 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,716 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:38,718 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,718 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:38,734 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,735 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:40:38,736 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:38,737 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:40:38,737 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:40:38,776 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:40:38,882 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:40:59,057 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:40:59,073 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:40:59,078 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,078 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:59,079 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:40:59,081 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,082 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:59,086 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,086 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:59,174 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,175 - root - INFO - base_adapter.py:59 - 执行成功,返回值：19
2020-12-20 04:40:59,179 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:40:59,181 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,181 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:59,188 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,188 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:40:59,298 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,298 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:40:59,299 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:40:59,301 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:40:59,301 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:40:59,301 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:41:19,433 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:41:19,438 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:41:19,445 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,445 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:19,446 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:41:19,448 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,448 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:19,450 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,450 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:19,491 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,494 - root - INFO - base_adapter.py:59 - 执行成功,返回值：20
2020-12-20 04:41:19,500 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,500 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:19,507 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,508 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:19,541 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:41:19,646 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:41:19,788 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,788 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:41:19,790 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:19,790 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:41:19,791 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:41:39,781 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:41:39,795 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:41:39,798 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,799 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:39,799 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:41:39,801 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,801 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:39,808 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,808 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:39,836 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,836 - root - INFO - base_adapter.py:59 - 执行成功,返回值：21
2020-12-20 04:41:39,839 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,840 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:39,842 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,843 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:41:39,861 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,861 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:41:39,863 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:41:39,863 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:41:39,863 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:41:39,907 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:41:40,019 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:42:00,145 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:42:00,151 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:42:00,163 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,164 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:00,164 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:42:00,167 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,167 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:00,170 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,170 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:00,196 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,196 - root - INFO - base_adapter.py:59 - 执行成功,返回值：22
2020-12-20 04:42:00,199 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,200 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:00,202 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,203 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:00,224 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,224 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:42:00,227 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:00,228 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:42:00,228 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:42:00,259 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:42:00,363 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:42:20,501 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:42:20,508 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:42:20,512 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,512 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:20,512 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:42:20,515 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,515 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:20,519 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,519 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:20,546 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,546 - root - INFO - base_adapter.py:59 - 执行成功,返回值：23
2020-12-20 04:42:20,549 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,549 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:20,552 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,552 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:20,569 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,570 - root - INFO - base_adapter.py:59 - 执行成功,返回值：-1
2020-12-20 04:42:20,573 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:20,575 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1924
2020-12-20 04:42:20,576 - root - ERROR - base_adapter.py:219 - NET_DVR_SetupAlarmChan_V41 报警布防: the error code is 1924
2020-12-20 04:42:20,614 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:42:20,716 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:42:46,064 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:42:46,332 - root - INFO - gateway_server.py:249 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:42:46,388 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:46,389 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:46,389 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:42:46,392 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:46,392 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:46,394 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:46,394 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:46,466 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:42:46,569 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:42:46,672 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:42:46,724 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:46,726 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:42:46,730 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:46,731 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:46,733 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:46,733 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:42:46,756 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:42:46,756 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:42:46,780 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:42:46,883 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:42:46,986 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:43:07,122 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:43:07,231 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:43:07,336 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:43:27,467 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:43:27,573 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:43:27,677 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:43:47,817 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:43:47,923 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:43:48,026 - root - WARNING - gateway_server.py:257 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:43:57,637 - root - INFO - main.py:63 - START SERVER
2020-12-20 04:43:57,914 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:43:57,936 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:43:57,938 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:43:57,938 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:43:57,940 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:43:57,941 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:43:57,943 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:43:57,943 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:43:58,017 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:43:58,119 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:43:58,188 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:43:58,188 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:43:58,191 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:43:58,191 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:43:58,193 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:43:58,194 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:43:58,218 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:43:58,218 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:43:58,221 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:43:58,327 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:43:58,442 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:43:58,546 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:44:14,389 - root - ERROR - task_controler.py:465 - get no user by code 0
2020-12-20 04:44:18,671 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:44:18,774 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:44:18,876 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:44:39,002 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:44:39,109 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:44:39,219 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:44:40,453 - root - ERROR - task_controler.py:465 - get no user by code 1
2020-12-20 04:44:48,291 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:48,291 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:44:48,321 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:48,322 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:44:48,684 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:48,685 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:44:49,387 - root - WARNING - gateway_server.py:106 - equipment (192.168.8.172, 8000) is offline
2020-12-20 04:44:59,348 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:44:59,457 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
2020-12-20 04:44:59,569 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:44:59,577 - root - INFO - gateway_server.py:244 - 服务端(('192.168.8.172', 8000))已成功连接。。online
2020-12-20 04:44:59,585 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:59,586 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:44:59,586 - root - INFO - base_adapter.py:74 - SDK初始化成功
2020-12-20 04:44:59,588 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:59,588 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:44:59,590 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:59,590 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:44:59,980 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:59,981 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:44:59,985 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:59,986 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:44:59,987 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:44:59,988 - root - INFO - base_adapter.py:59 - 执行成功,返回值：1
2020-12-20 04:45:00,024 - root - INFO - base_adapter.py:58 - 调用的库：/home/alex/PycharmProjects/ToolManageSys/util/hkws/../libs/hkvision_lib/libhcnetsdk.so
2020-12-20 04:45:00,025 - root - INFO - base_adapter.py:59 - 执行成功,返回值：0
2020-12-20 04:45:19,703 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.118', 23)
2020-12-20 04:45:19,810 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 26)
2020-12-20 04:45:19,916 - root - WARNING - gateway_server.py:252 - fail to connect to server ('192.168.0.117', 23)
